---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-test-pod
spec:
  containers:
    - name: ebs-test-container
      image: busybox
      command: ["sh", "-c", "echo 'EBS CSI is working!' > /mnt/test/file.txt && sleep 3600"]
      volumeMounts:
        - name: ebs-storage
          mountPath: /mnt/test
  volumes:
    - name: ebs-storage
      persistentVolumeClaim:
        claimName: ebs-test-pvc
