apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::478253497479:role/EKSOperatorRole
      username: eks-operator
      groups:
      - system:masters
    - rolearn: arn:aws:iam::478253497479:role/gpu-e2e-cluster-node-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"# Operator Role → cluster admin\n- rolearn: arn:aws:iam::478253497479:role/EKSOperatorRole\n  username: eks-operator\n  groups:\n    - system:masters\n\n# Node Role → worker nodes\n- rolearn: arn:aws:iam::478253497479:role/EKSNodeRole\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2025-11-25T16:55:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "49755"
  uid: 0ed20d66-88a2-43b6-8e2a-ecf3ae17a3c9
