apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  restartPolicy: Never
  containers:
  - name: cuda-test
    image: nvcr.io/nvidia/cuda:12.2.0-base-ubuntu22.04
    command: ["/bin/bash", "-c"]
    args:
      - |
        echo "Running nvidia-smi..."
        nvidia-smi;
        sleep 3600
    resources:
      limits:
        nvidia.com/gpu: 1
